import { db } from '@/db';
import { operators } from '@/db/schema';
import type {
  ShikaraDetails, GuideDetails, VendorDetails,
  AccommodationDetails, HouseboatDetails,
} from '@/types';

const SEED_DATA: {
  slug: string; name: string; category: string; short_desc: string;
  whatsapp: string; lat: number; lng: number;
  shikara_details?: ShikaraDetails;
  guide_details?: GuideDetails;
  vendor_details?: VendorDetails;
  accommodation_details?: AccommodationDetails;
  houseboat_details?: HouseboatDetails;
  photos?: string[];
  pricing_note?: string;
  email?: string;
}[] = [
  // ========== SHIKARA ==========
  {
    slug: 'shikara-royal-cruise',
    name: 'Royal Shikara Cruise',
    category: 'shikara',
    short_desc: 'Luxury shikara tours on Dal & Nigeen lakes — sunset, garden, and heritage routes.',
    whatsapp: '+919100001111',
    email: 'royal@shikara.test',
    lat: 34.1105, lng: 74.8689,
    pricing_note: 'Prices vary by season and duration.',
    shikara_details: {
      full_name: 'Rashid Ahmed',
      mobile_number: '+919100001111',
      whatsapp_number: '+919100001111',
      shikara_number: 'SH-042',
      ghat_number: 'Ghat 1',
      operating_areas: ['Dal Lake', 'Nigeen Lake', 'Boulevard'],
      years_experience: '15',
      languages: ['English', 'Hindi', 'Urdu', 'Kashmiri'],
      services: ['Sunset Tour', 'Garden Tour', 'Heritage Tour', 'Full Day'],
      tour_duration: '1-6 hours',
      registered_shikara: 'Yes',
      registration_number: 'JK-SH-2024-042',
      price_per_ride: '1500',
      price_per_hour: '800',
      price_note: 'Includes life jackets and shikara blanket',
    },
    photos: ['/images/shikara-1.jpg'],
  },
  {
    slug: 'shikara-lotus-tours',
    name: 'Lotus Shikara Tours',
    category: 'shikara',
    short_desc: 'Guided shikara rides through the floating gardens of Dal Lake.',
    whatsapp: '+919100002222',
    email: 'lotus@shikara.test',
    lat: 34.1150, lng: 74.8750,
    shikara_details: {
      full_name: 'Imran Sheikh',
      mobile_number: '+919100002222',
      whatsapp_number: '+919100002222',
      shikara_number: 'SH-089',
      ghat_number: 'Ghat 3',
      operating_areas: ['Dal Lake'],
      years_experience: '10',
      languages: ['English', 'Hindi', 'Kashmiri'],
      services: ['Floating Market Tour', 'Sunrise Tour', 'Lotus Garden Ride'],
      tour_duration: '1-3 hours',
      registered_shikara: 'Yes',
      registration_number: 'JK-SH-2023-089',
      price_per_ride: '1200',
      price_per_hour: '600',
    },
  },
  {
    slug: 'shikara-mughal-ride',
    name: 'Mughal Garden Shikara',
    category: 'shikara',
    short_desc: 'Visit the Mughal Gardens from the water — the most scenic approach.',
    whatsapp: '+919100003333',
    lat: 34.1080, lng: 74.8780,
    shikara_details: {
      full_name: 'Faisal Khan',
      mobile_number: '+919100003333',
      shikara_number: 'SH-112',
      ghat_number: 'Ghat 5',
      operating_areas: ['Dal Lake'],
      years_experience: '8',
      languages: ['English', 'Hindi', 'Kashmiri'],
      services: ['Garden Tour', 'Photography Tour'],
      tour_duration: '2-4 hours',
      registered_shikara: 'Yes',
      registration_number: 'JK-SH-2024-112',
      price_per_ride: '1800',
      price_per_hour: '900',
    },
  },
  {
    slug: 'shikara-twilight-float',
    name: 'Twilight Shikara Float',
    category: 'shikara',
    short_desc: 'Evening shikara experience with Kashmiri kahwa and sunset views.',
    whatsapp: '+919100004444',
    lat: 34.1120, lng: 74.8720,
    shikara_details: {
      full_name: 'Bilal Mir',
      mobile_number: '+919100004444',
      shikara_number: 'SH-156',
      ghat_number: 'Ghat 2',
      operating_areas: ['Dal Lake', 'Nigeen Lake'],
      years_experience: '12',
      languages: ['English', 'Hindi', 'Kashmiri', 'Punjabi'],
      services: ['Sunset Tour', 'Kahwa Ride', 'Candlelight Dinner'],
      tour_duration: '1-2 hours',
      registered_shikara: 'Yes',
      registration_number: 'JK-SH-2023-156',
      price_per_ride: '2000',
      price_per_hour: '1000',
    },
  },
  {
    slug: 'shikara-char-chinar',
    name: 'Char Chinar Shikara',
    category: 'shikara',
    short_desc: 'Visit the iconic Char Chinar island on a guided shikara tour.',
    whatsapp: '+919100005555',
    lat: 34.1200, lng: 74.8650,
    shikara_details: {
      full_name: 'Zubair Wani',
      mobile_number: '+919100005555',
      shikara_number: 'SH-201',
      ghat_number: 'Ghat 4',
      operating_areas: ['Dal Lake'],
      years_experience: '20',
      languages: ['English', 'Hindi', 'Urdu', 'Kashmiri', 'Arabic'],
      services: ['Char Chinar Tour', 'Full Lake Tour', 'Sunrise Trip'],
      tour_duration: '2-5 hours',
      registered_shikara: 'Yes',
      registration_number: 'JK-SH-2024-201',
      price_per_ride: '2500',
      price_per_hour: '900',
      price_note: 'Char Chinar tour includes 30-min stop at island',
    },
  },

  // ========== GUIDE ==========
  {
    slug: 'guide-hassan-wani',
    name: 'Hassan Wani — Heritage Walks',
    category: 'guide',
    short_desc: 'Licensed local guide specializing in Old Srinagar heritage walks and food tours.',
    whatsapp: '+919100006666',
    email: 'hassan@guide.test',
    lat: 34.0740, lng: 74.8060,
    pricing_note: 'Half-day: ₹1500, Full-day: ₹2500',
    guide_details: {
      full_name: 'Hassan Wani',
      contact_number: '+919100006666',
      whatsapp_number: '+919100006666',
      email: 'hassan@guide.test',
      languages: ['English', 'Hindi', 'Kashmiri', 'Urdu'],
      specialties: ['Heritage Walks', 'Food Tours', 'History', 'Photography'],
      years_experience: '18',
      certification: 'JK Tourism Licensed Guide — License #G-2019-045',
      operating_areas: ['Old Srinagar', 'Dal Lake', 'Mughal Gardens', 'Pari Mahal'],
      google_maps: 'https://maps.app.goo.gl/example1',
    },
    photos: ['/images/guide-1.jpg'],
  },
  {
    slug: 'guide-lakeside-sarah',
    name: 'Sarah Mir — Lake & Garden Tours',
    category: 'guide',
    short_desc: 'Female guide offering tailored tours for women travelers and families.',
    whatsapp: '+919100007777',
    lat: 34.1100, lng: 74.8600,
    guide_details: {
      full_name: 'Sarah Mir',
      contact_number: '+919100007777',
      whatsapp_number: '+919100007777',
      languages: ['English', 'Hindi', 'Kashmiri'],
      specialties: ['Women-Only Tours', 'Garden Tours', 'Family Tours', 'Shopping Tours'],
      years_experience: '7',
      certification: 'JK Tourism Licensed Guide — License #G-2022-112',
      operating_areas: ['Dal Lake', 'Mughal Gardens', 'Downtown Srinagar', 'Polo View'],
    },
  },
  {
    slug: 'guide-adventure-bilal',
    name: 'Bilal Lone — Trek & Trail',
    category: 'guide',
    short_desc: 'Certified adventure guide for treks around Srinagar, Sonamarg, and Pahalgam.',
    whatsapp: '+919100008888',
    lat: 34.0600, lng: 74.8200,
    guide_details: {
      full_name: 'Bilal Lone',
      contact_number: '+919100008888',
      whatsapp_number: '+919100008888',
      languages: ['English', 'Hindi', 'Kashmiri'],
      specialties: ['Trekking', 'Camping', 'Wildlife', 'Bird Watching'],
      years_experience: '10',
      certification: 'JMT Adventure Guide Certified — 2021',
      operating_areas: ['Sonamarg', 'Pahalgam', 'Dachigam', 'Harwan'],
    },
  },

  // ========== VENDOR ==========
  {
    slug: 'vendor-pashmina-house',
    name: 'Kashmir Pashmina House',
    category: 'vendor',
    short_desc: 'Authentic Pashmina shawls, carpets, and handcrafted souvenirs from Srinagar.',
    whatsapp: '+919100009999',
    email: 'info@pashmina.test',
    lat: 34.0730, lng: 74.8050,
    vendor_details: {
      business_name: 'Kashmir Pashmina House',
      owner_name: 'Ghulam Mohammad',
      contact_number: '+919100009999',
      whatsapp_number: '+919100009999',
      email: 'info@pashmina.test',
      business_type: 'Handicrafts & Textiles',
      specialties: ['Pashmina Shawls', 'Silk Carpets', 'Paper Machie', 'Wood Carving'],
      operating_areas: ['Polo View', 'Lal Chowk', 'Old City'],
      google_maps: 'https://maps.app.goo.gl/example2',
    },
    photos: ['/images/vendor-1.jpg'],
  },
  {
    slug: 'vendor-saffron-king',
    name: 'Saffron King — Kashmiri Spices',
    category: 'vendor',
    short_desc: 'Premium Kashmiri saffron, spices, dry fruits, and traditional condiments.',
    whatsapp: '+919100001010',
    lat: 34.0745, lng: 74.8070,
    vendor_details: {
      business_name: 'Saffron King',
      owner_name: 'Ahmad Bhat',
      contact_number: '+919100001010',
      business_type: 'Spices & Dry Fruits',
      specialties: ['Kashmiri Saffron', 'Dry Fruits', 'Kahwa', 'Spice Boxes', 'Walnuts'],
      operating_areas: ['Lal Chowk', 'Baton Mall', 'Nowhatta'],
    },
  },
  {
    slug: 'vendor-silk-route',
    name: 'Silk Route Carpets',
    category: 'vendor',
    short_desc: 'Handwoven Kashmiri silk carpets, kilims, and chain-stitch rugs since 1985.',
    whatsapp: '+919100001111',
    lat: 34.0750, lng: 74.8080,
    vendor_details: {
      business_name: 'Silk Route Carpets',
      owner_name: 'Fayaz Ahmad',
      contact_number: '+919100001111',
      email: 'fayaz@silkroute.test',
      business_type: 'Carpets & Rugs',
      specialties: ['Silk Carpets', 'Chain Stitch', 'Kilims', 'Namdha Felt'],
      operating_areas: ['Polo View', 'Zainakadal', 'Boulevard'],
    },
  },

  // ========== HOMESTAY ==========
  {
    slug: 'homestay-gulab-nivas',
    name: 'Gulab Niwas Homestay',
    category: 'homestay',
    short_desc: 'Traditional Kashmiri family home near Dal Lake — home-cooked meals included.',
    whatsapp: '+919100002020',
    email: 'gulab@homestay.test',
    lat: 34.1050, lng: 74.8700,
    pricing_note: '₹2500/night single, ₹3500/night double including breakfast & dinner',
    accommodation_details: {
      property_type: 'homestay',
      owner_name: 'Gulab Khan',
      manager_name: 'Sameer Khan',
      contact: '+919100002020',
      email: 'gulab@homestay.test',
      address: 'Ghat 1 Road, Dal Lake, Srinagar',
      total_rooms: '4',
      room_types: ['Single', 'Double', 'Family Suite'],
      pricing_single: '2500',
      pricing_double: '3500',
      amenities: ['WiFi', 'Hot Water', 'Home-Cooked Meals', 'Garden', 'Parking', 'Heater'],
      meals_included: ['Breakfast', 'Dinner'],
      check_in: '12:00 PM',
      check_out: '10:00 AM',
      languages: ['English', 'Hindi', 'Kashmiri'],
      nearby_attractions: 'Dal Lake (5 min walk), Shalimar Garden (2 km), Boulevard (1 km)',
      google_maps: 'https://maps.app.goo.gl/example3',
    },
    photos: ['/images/homestay-1.jpg'],
  },
  {
    slug: 'homestay-meadow-view',
    name: 'Meadow View Homestay',
    category: 'homestay',
    short_desc: 'Peaceful homestay in Nishat area with stunning garden views.',
    whatsapp: '+919100003030',
    lat: 34.1250, lng: 74.8800,
    accommodation_details: {
      property_type: 'homestay',
      owner_name: 'Rafiq Sheikh',
      contact: '+919100003030',
      address: 'Nishat Garden Road, Srinagar',
      total_rooms: '3',
      room_types: ['Double', 'Twin'],
      pricing_single: '2000',
      pricing_double: '3000',
      amenities: ['WiFi', 'Hot Water', 'Garden View', 'Parking', 'Bonfire'],
      meals_included: ['Breakfast'],
      check_in: '1:00 PM',
      check_out: '11:00 AM',
      languages: ['English', 'Hindi'],
      nearby_attractions: 'Nishat Garden (500m), Dal Lake (3 km), Shankaracharya (4 km)',
    },
  },

  // ========== GUEST HOUSE ==========
  {
    slug: 'guesthouse-pine-valley',
    name: 'Pine Valley Guest House',
    category: 'guest_house',
    short_desc: 'Comfortable guest house near Dal Lake with mountain views and attached bathrooms.',
    whatsapp: '+919100004040',
    email: 'pine@guesthouse.test',
    lat: 34.1080, lng: 74.8650,
    pricing_note: '₹1500/night single, ₹2500/night double (room only)',
    accommodation_details: {
      property_type: 'guest_house',
      owner_name: 'Asif Mir',
      manager_name: 'Tariq Mir',
      contact: '+919100004040',
      email: 'pine@guesthouse.test',
      address: 'Boulevard Road, Dal Lake, Srinagar',
      total_rooms: '8',
      room_types: ['Single', 'Double', 'Triple', 'Dormitory'],
      pricing_single: '1500',
      pricing_double: '2500',
      amenities: ['WiFi', 'Hot Water', 'Restaurant', 'Room Service', 'Parking', 'Laundry'],
      meals_included: ['Breakfast'],
      check_in: '12:00 PM',
      check_out: '10:00 AM',
      languages: ['English', 'Hindi', 'Kashmiri', 'Urdu'],
      nearby_attractions: 'Dal Lake (2 min walk), Boulevard (walking distance), Nehru Park (1 km)',
      google_maps: 'https://maps.app.goo.gl/example4',
    },
    photos: ['/images/guesthouse-1.jpg'],
  },
  {
    slug: 'guesthouse-alpine-retreat',
    name: 'Alpine Retreat Guest House',
    category: 'guest_house',
    short_desc: 'Budget-friendly guest house in Rajbagh with easy access to the city center.',
    whatsapp: '+919100005050',
    lat: 34.0600, lng: 74.8000,
    accommodation_details: {
      property_type: 'guest_house',
      owner_name: 'Javid Dar',
      contact: '+919100005050',
      address: 'Rajbagh Main Road, Srinagar',
      total_rooms: '6',
      room_types: ['Single', 'Double'],
      pricing_single: '1200',
      pricing_double: '2000',
      amenities: ['WiFi', 'Hot Water', 'TV', 'Parking', 'Kitchen Access'],
      meals_included: [],
      check_in: '12:00 PM',
      check_out: '10:00 AM',
      languages: ['English', 'Hindi', 'Kashmiri'],
      nearby_attractions: 'Lal Chowk (3 km), Mughal Gardens (5 km), Dal Lake (6 km)',
    },
  },
  {
    slug: 'guesthouse-himalayan-view',
    name: 'Himalayan View Guest House',
    category: 'guest_house',
    short_desc: 'Guest house with panoramic Himalayan views, rooftop seating, and bonfire nights.',
    whatsapp: '+919100006060',
    lat: 34.1300, lng: 74.8550,
    accommodation_details: {
      property_type: 'guest_house',
      owner_name: 'Omar Reshi',
      contact: '+919100006060',
      address: 'Harwan Road, Srinagar',
      total_rooms: '10',
      room_types: ['Double', 'Deluxe Double', 'Family Room'],
      pricing_single: '1800',
      pricing_double: '2800',
      amenities: ['WiFi', 'Hot Water', 'Rooftop Terrace', 'Bonfire', 'Restaurant', 'Parking'],
      meals_included: ['Breakfast', 'Dinner'],
      check_in: '2:00 PM',
      check_out: '11:00 AM',
      languages: ['English', 'Hindi', 'Kashmiri'],
      nearby_attractions: 'Harwan Garden (1 km), Shalimar Bagh (2 km), Dal Lake (4 km)',
    },
  },
];

async function main() {
  let inserted = 0;

  for (const op of SEED_DATA) {
    try {
      const details_column = op.shikara_details ? 'shikara_details' :
        op.guide_details ? 'guide_details' :
        op.vendor_details ? 'vendor_details' : 'accommodation_details';
      const details_value = op.shikara_details || op.guide_details || op.vendor_details || op.accommodation_details;

      await db.insert(operators).values({
        slug: op.slug,
        name: op.name,
        category: op.category as any,
        short_desc: op.short_desc,
        whatsapp: op.whatsapp,
        email: op.email || null,
        lat: op.lat,
        lng: op.lng,
        status: 'approved',
        hidden: false,
        verified: true,
        plan: 'free',
        lead_month: 0,
        photos: op.photos || [],
        pricing_note: op.pricing_note || null,
        [details_column]: details_value,
      }).onConflictDoNothing({ target: operators.slug });

      inserted++;
      console.log(`Inserted: ${op.name}`);
    } catch (e: any) {
      console.error(`Failed: ${op.name} — ${e.message || e}`);
    }
  }

  console.log(`\nDone. Inserted: ${inserted} of ${SEED_DATA.length}`);
}

main().catch(console.error);
